# Generated by Django 4.1.1 on 2022-09-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcreate',
            name='contact',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='accountcreate',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
