# Generated by Django 4.0.5 on 2022-09-13 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PetoCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('petname', models.CharField(max_length=15)),
                ('species', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=10)),
            ],
        ),
    ]
