# Generated by Django 4.1.1 on 2022-09-16 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_petocreate_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petocreate',
            name='petname',
            field=models.CharField(max_length=50),
        ),
    ]
