# Generated by Django 4.1.1 on 2022-09-16 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_petocreate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petocreate',
            name='image',
            field=models.ImageField(null=True, upload_to='./peto/images'),
        ),
    ]
