# Generated by Django 4.1.1 on 2022-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_petocreate_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petocreate',
            name='image',
        ),
        migrations.AddField(
            model_name='petocreate',
            name='imageAnimal',
            field=models.ImageField(null=True, upload_to='peto/images'),
        ),
    ]
