# Generated by Django 4.1.1 on 2022-09-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_petocreate_image_petocreate_imageanimal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petocreate',
            old_name='imageAnimal',
            new_name='image',
        ),
    ]
