# Generated by Django 4.1.1 on 2022-09-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_petocreate_age_alter_petocreate_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petocreate',
            name='petname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='petocreate',
            name='species',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
